- name: import custom zabbix templates
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    template_json: "{{ lookup('file', \"{{ item }}\" + '.json') }}"
    state: present
  loop: "{{ (zabbix_templates + zabbix_templates_custom) | flatten(levels=1) }}"
